package com.sedsoftware.tackle.utils

object FileUtils {

    private val audio: Map<String, String> by lazy {
        mapOf(
            "aac" to "audio/aac",
            "adp" to "audio/adpcm",
            "aif" to "audio/x-aiff",
            "aifc" to "audio/x-aiff",
            "aiff" to "audio/x-aiff",
            "au" to "audio/basic",
            "dts" to "audio/vnd.dts",
            "flac" to "audio/flac",
            "kar" to "audio/midi",
            "m2a" to "audio/m2a",
            "m3a" to "audio/m3a",
            "m3u" to "audio/x-mpegurl",
            "m4a" to "audio/m4a",
            "mid" to "audio/midi",
            "midi" to "audio/midi",
            "mp2" to "audio/mp2",
            "mp2a" to "audio/mp2a",
            "mp3" to "audio/mp3",
            "mp4a" to "audio/mp4a",
            "mpga" to "audio/mpeg",
            "oga" to "audio/ogg",
            "ogg" to "audio/ogg",
            "opus" to "audio/ogg",
            "ra" to "audio/x-pn-realaudio",
            "ram" to "audio/x-pn-realaudio",
            "rmi" to "audio/midi",
            "rmp" to "audio/x-pn-realaudio-plugin",
            "snd" to "audio/basic",
            "spx" to "audio/ogg",
            "wav" to "audio/x-wav",
            "wax" to "audio/x-ms-wax",
            "wma" to "audio/x-ms-wma",
        )
    }

    private val images: Map<String, String> by lazy {
        mapOf(
            "avif" to "image/avif",
            "bmp" to "image/bmp",
            "btif" to "image/prs.btif",
            "cgm" to "image/cgm",
            "cmx" to "image/x-cmx",
            "djv" to "image/vnd.djvu",
            "djvu" to "image/vnd.djvu",
            "dwg" to "image/vnd.dwg",
            "dxf" to "image/vnd.dxf",
            "fbs" to "image/vnd.fastbidsheet",
            "fh" to "image/x-freehand",
            "fh4" to "image/x-freehand",
            "fh5" to "image/x-freehand",
            "fh7" to "image/x-freehand",
            "fhc" to "image/x-freehand",
            "fpx" to "image/vnd.fpx",
            "fst" to "image/vnd.fst",
            "g3" to "image/g3fax",
            "gif" to "image/gif",
            "heic" to "image/heic",
            "heif" to "image/heif",
            "ico" to "image/x-icon",
            "ief" to "image/ief",
            "jpe" to "image/jpeg",
            "jpeg" to "image/jpeg",
            "jpg" to "image/jpeg",
            "mdi" to "image/vnd.ms-modi",
            "mmr" to "image/vnd.fujixerox.edmics-mmr",
            "npx" to "image/vnd.net-fpx",
            "pbm" to "image/x-portable-bitmap",
            "pct" to "image/x-pict",
            "pcx" to "image/x-pcx",
            "pgm" to "image/x-portable-graymap",
            "pic" to "image/x-pict",
            "png" to "image/png",
            "pnm" to "image/x-portable-anymap",
            "ppm" to "image/x-portable-pixmap",
            "psd" to "image/vnd.adobe.photoshop",
            "ras" to "image/x-cmu-raster",
            "rgb" to "image/x-rgb",
            "rlc" to "image/vnd.fujixerox.edmics-rlc",
            "svg" to "image/svg+xml",
            "svgz" to "image/svg+xml",
            "tif" to "image/tiff",
            "tiff" to "image/tiff",
            "wbmp" to "image/vnd.wap.wbmp",
            "webp" to "image/webp",
            "xbm" to "image/x-xbitmap",
            "xif" to "image/vnd.xiff",
            "xpm" to "image/x-xpixmap",
            "xwd" to "image/x-xwindowdump",
        )
    }

    private val video: Map<String, String> by lazy {
        mapOf(
            "3g2" to "video/3gpp2",
            "3gp" to "video/3gpp",
            "asf" to "video/x-ms-asf",
            "asx" to "video/x-ms-asf",
            "avi" to "video/x-msvideo",
            "f4v" to "video/x-f4v",
            "fli" to "video/x-fli",
            "flv" to "video/x-flv",
            "fvt" to "video/vnd.fvt",
            "h261" to "video/h261",
            "h263" to "video/h263",
            "h264" to "video/h264",
            "jpgm" to "video/jpm",
            "jpgv" to "video/jpeg",
            "jpm" to "video/jpm",
            "m1v" to "video/mpeg",
            "m2v" to "video/mpeg",
            "m4u" to "video/vnd.mpegurl",
            "m4v" to "video/x-m4v",
            "mj2" to "video/mj2",
            "mjp2" to "video/mj2",
            "mkv" to "video/x-matroska",
            "mov" to "video/quicktime",
            "mp4" to "video/mp4",
            "mp4v" to "video/mp4",
            "mpa" to "video/mpeg",
            "mpe" to "video/mpeg",
            "mpeg" to "video/mpeg",
            "mpg" to "video/mpeg",
            "mpg4" to "video/mp4",
            "mpv" to "video/x-matroska",
            "mxu" to "video/vnd.mpegurl",
            "ogv" to "video/ogg",
            "pyv" to "video/vnd.ms-playready.media.pyv",
            "qt" to "video/quicktime",
            "viv" to "video/vnd.vivo",
            "webm" to "video/webm",
            "wm" to "video/x-ms-wm",
            "wmv" to "video/x-ms-wmv",
            "wmx" to "video/x-ms-wmx",
            "wvx" to "video/x-ms-wvx",
        )
    }

    private val other: Map<String, String> by lazy {
        mapOf(
            "pdf" to "application/pdf",
            "swf" to "application/x-shockwave-flash",
            "class" to "application/java",
            "tar" to "application/x-tar",
            "zip" to "application/zip",
            "gz" to "application/x-gzip",
            "gzip" to "application/x-gzip",
            "rar" to "application/rar",
            "7z" to "application/x-7z-compressed",
            "doc" to "application/msword",
            "pot" to "application/vnd.ms-powerpoint",
            "pps" to "application/vnd.ms-powerpoint",
            "ppt" to "application/vnd.ms-powerpoint",
            "wri" to "application/vnd.ms-write",
            "xla" to "application/vnd.ms-excel",
            "xls" to "application/vnd.ms-excel",
            "xlt" to "application/vnd.ms-excel",
            "xlw" to "application/vnd.ms-excel",
            "mdb" to "application/vnd.ms-access",
            "mpp" to "application/vnd.ms-project",
            "docx" to "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "docm" to "application/vnd.ms-word.document.macroEnabled.12",
            "dotx" to "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
            "dotm" to "application/vnd.ms-word.template.macroEnabled.12",
            "xlsx" to "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "xlsm" to "application/vnd.ms-excel.sheet.macroEnabled.12",
            "xlsb" to "application/vnd.ms-excel.sheet.binary.macroEnabled.12",
            "xltx" to "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
            "xltm" to "application/vnd.ms-excel.template.macroEnabled.12",
            "xlam" to "application/vnd.ms-excel.addin.macroEnabled.12",
            "pptx" to "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            "pptm" to "application/vnd.ms-powerpoint.presentation.macroEnabled.12",
            "ppsx" to "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
            "ppsm" to "application/vnd.ms-powerpoint.slideshow.macroEnabled.12",
            "potx" to "application/vnd.openxmlformats-officedocument.presentationml.template",
            "potm" to "application/vnd.ms-powerpoint.template.macroEnabled.12",
            "ppam" to "application/vnd.ms-powerpoint.addin.macroEnabled.12",
            "sldx" to "application/vnd.openxmlformats-officedocument.presentationml.slide",
            "sldm" to "application/vnd.ms-powerpoint.slide.macroEnabled.12",
            "onetoc" to "application/onenote",
            "onetoc2" to "application/onenote",
            "onetmp" to "application/onenote",
            "onepkg" to "application/onenote",
            "oxps" to "application/oxps",
            "xps" to "application/vnd.ms-xpsdocument",
            "odt" to "application/vnd.oasis.opendocument.text",
            "odp" to "application/vnd.oasis.opendocument.presentation",
            "ods" to "application/vnd.oasis.opendocument.spreadsheet",
            "odg" to "application/vnd.oasis.opendocument.graphics",
            "odc" to "application/vnd.oasis.opendocument.chart",
            "odb" to "application/vnd.oasis.opendocument.database",
            "odf" to "application/vnd.oasis.opendocument.formula",
        )
    }

    fun getMimeTypeByExtension(ext: String): String {
        val key: String = ext.lowercase()
        return when {
            images.containsKey(key) -> images[key]!!
            video.containsKey(key) -> video[key]!!
            audio.containsKey(key) -> audio[key]!!
            other.containsKey(key) -> other[key]!!
            else -> "application/octet-stream"
        }
    }
}
