name: AnalysisAndTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Analyze and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - uses: gradle/gradle-build-action@v3
        with:
          cache-disabled: true

      - name: Code analysis
        run: ./gradlew detekt

      - name: Testing
        run: ./gradlew testDebugUnitTest
